### ISSUE TITLE
Missing stylesheet?

### ISSUE THREAD

**Issue by stemuk** [deepstreamIO/golden-layout-website#1]
The website seems to be unstyled right now, at least Safari on iOS only shows the bare HTML. Is this true for Chrome, Firefox etc. on Desktop as well?

**Comment by yasserf** [comment]
Thank you for noticing! I'm currently trying to automate the website build so that it can get published on tags. Unfortunately the build is ever so slightly complicated. Looking into it now

**Comment by yasserf** [comment]
Fixed. Turned out website generator wasn't linux/mac friendly and that just screwed things up. Also fiddled a bit with some other stuff in the process. Might be good to get a sanity check!
